quiz task
DenisHedgehog/quiz-task pull request #1
Opened 2018-08-17 11:20 UTC by DenisHedgehog

2018-08-17 12:51 UTC, KrickRay commented on src/components/AnswerItem.jsx
> +                <input name="answerItem" type="radio" onClick={() => this.props.onClick(this.props.answer.id)}/>
есть минус при инициализации функций в рендере, они будут инициализироваться каждый раз при перерисовке и загромождают функцию рендер, лучше их выносить в отдельный метод

2018-08-17 12:51 UTC, KrickRay commented on src/components/AnswerList.jsx
> +                onClick={this.onAnswerChange.bind(this)} />);
так же не очень хорошо биндить в рендере, можешь прочесть https://reactjs.org/docs/handling-events.html

2018-08-17 12:51 UTC, KrickRay commented on src/components/AnswerStatus.jsx
> +        } else {
бесполезный `else`

2018-08-17 12:51 UTC, KrickRay commented on src/components/AnswerStatus.jsx
> +        } else {
раз есть дефолтный

2018-08-17 12:51 UTC, KrickRay commented on src/components/Progress.jsx
> +            <p className="progress text text_color_light"><span className="text_bold text_color_mid">{this.props.progress}</span> of <span className="text_bold text_color_mid">{this.props.questionCou
нельзя использовать сразу два блока и прогресс и текст

2018-08-17 12:51 UTC, KrickRay commented on src/components/Progress.jsx
> +            <p className="progress text text_color_light"><span className="text_bold text_color_mid">{this.props.progress}</span> of <span className="text_bold text_color_mid">{this.props.questionCou
по факту компонент равно блок

2018-08-17 12:51 UTC, KrickRay commented on src/components/Progress.jsx
> +            <p className="progress text text_color_light"><span className="text_bold text_color_mid">{this.props.progress}</span> of <span className="text_bold text_color_mid">{this.props.questionCou
если есть блок текст, то ему нужно завести свой компонент

2018-08-17 12:51 UTC, KrickRay commented on src/components/Quiz.jsx
> +    componentWillMount() {
`componentWillMount` уже не стоит использовать

так выглядит новый лайфсайсл реакта

![image](https://user-images.githubusercontent.com/11846445/44266954-19865300-a235-11e8-8ddf-9deebb57dd99.png)

2018-08-17 12:59 UTC, KrickRay commented on src/components/Quiz.jsx
> +                {this.isPictureExist() ? <Picture img={this.props.questions[this.state.step].img} /> : ''}
есть более простая запись - `{this.isPictureExist() && <Picture img={this.props.questions[this.state.step].img} />}` благодаря тому, что null, undefined и boolean не рендаряться

2018-08-17 13:08 UTC, KrickRay commented on src/components/Quiz.jsx
> +    changeStyles() {
функция не говорит о том, что именно меняется в стилях

2018-08-17 13:18 UTC, KrickRay commented on src/components/Quiz.jsx
> +                step: prevState.step + 1,
https://reactjs.org/docs/state-and-lifecycle.html#using-state-correctly

2018-08-17 13:42 UTC, KeinAsylum requested changes
* хочется выделять правильный ответ, кликая на плашку с ответом, а не только в checkbox.
* проблема с responsive видом
* после ответа, на следующем вопросе остается 
 выделенный checkbox

2018-08-17 13:42 UTC, KeinAsylum commented on webpack.dev.js
> +        new CopyWebpackPlugin([{from: './questions.json', to: './dist'}])
Copy нужно делать для всех сборок

2018-08-17 13:42 UTC, KeinAsylum commented on src/index.js
> +async function getQuestions() {
Сложно, можно:
```javascript
function getQuestions() {
    return fetch('questions.json').then((res) => res.json());
}
```

2018-08-17 13:42 UTC, KeinAsylum commented on src/App.jsx
> +export default class App extends React.Component {
В случаях, когда в компоненте нет работы со state, лучше использовать  stateless компоненты. Это может выглядеть так:
```javascript
const App = ({ questions }) => (
    <div className="app text text_color_light">
        <Quiz questions={questions} />
    </div>
);

export default App;
```

2018-08-17 13:42 UTC, KeinAsylum commented on src/App.jsx
> +                <Quiz questions={this.props.questions} />
Смысл вводить `Quiz` компонент?

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +        return (this.state.step < this.props.questions.length) ? (
Тут явно выделяются 2 отдельных компонента: Первый обрабатывающий вопросы, второй результат

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +    componentWillMount() {
Инициализацию state нужно производить в конструкторе компонента.

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +        this.setState(prevState => {
1. Не обязательно переопределять весь state, можно только необходимый кусок:
```javascript
this.setState({stage});
```

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +                    onAnswerChange={this.onAnswerChange.bind(this)}
`bind` методов нужно делать в конструкторе компонента

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +            answerStyles: ["answer", "answer", "answer"],
Не очень удачная структура. Что если будет больше 3х ответов на вопрос. 
И похоже на то, что стили должны вычисляться на уровне answer компонента

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/AnswerList.jsx
> +            <div>
Непонятный div

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Progress.jsx
> +            <p className="progress text text_color_light"><span className="text_bold text_color_mid">{this.props.progress}</span> of <span className="text_bold text_color_mid">{this.props.questionCou
Что то с форматированием

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/AnswerList.jsx
> +export default class AnswerList extends React.Component {
Может лучше OptionList

2018-08-17 13:42 UTC, KeinAsylum commented on src/components/Quiz.jsx
> +            stage: "Answer"
Не совсем понятно что такое stage и его значения

2018-08-23 11:16 UTC, KeinAsylum requested changes
* Используй стрелочные функции в stateless компонентах
* Сложно понять какие атрибуты у компонента являются свойствами, а какие callback. Необходимо использовать именование `handle` и `on`
Подробнее смысл описан тут: https://reactjs.org/docs/lifting-state-up.html

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/App.jsx
> +    increaseProgress() {
Для ясности лучше использовать соглашение по именованию:
Функции обработчики называть в стиле `handleSomething`
Свойства компонента, которым назначаются обработчики`onSomethingChange`

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/App.jsx
> +        this.setState(prevState => {
Можно делать более короткую запись:
```javascript
this.setState((prevState) => ({
    currentQuestionId: prevState.currentQuestionId + 1
}));
```

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/App.jsx
> +                <Question question={this.props.questions[this.state.currentQuestionId]} />
`this.props.questions[this.state.currentQuestionId]` - это отдельное действие, его лучше поместить в отдельную функцию

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/App.jsx
> +            <div className="app">
Лучше выделить в отдельный компонент

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/Question.jsx
> +function Question(props) {
Очень удобно использовать запись вида:
`const {...} = object;`

```javascript
const Question = (props) => {
    const { question: { question, img } } = props;
    return (
        <div className="question">
            <Text text={question} />
            {img.length > 0 && <Picture img={img} />}
        </div>
    )
};
```

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/Button.jsx
> +function Button(props) {
Используй стрелочные функции, они короче.

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/App.jsx
> +                score: prevState.score + 1
increaseProgress меняет состояние score, также есть компонент `Progress` с атрибутом `progress`. Но в `progress` устанавливается `this.state.currentQuestionId + 1`. Как то все очень сложно

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/Progress.jsx
> +export default class Progress extends React.Component {
Можно сделать stateless компонент

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/Progress.jsx
> +            <p className="progress text_color_light"><span className="text_bold text_color_mid">{this.props.progress}</span> of <span className="text_bold text_color_mid">{this.props.questionCount}</
С форматированием беда

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/OptionList.jsx
> +        const optionList = this.props.options.map(option =>
Можно делать сразу return

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/OptionList.jsx
> +        const optionList = this.props.options.map(option =>
Ставятся скобки `(option)  =>`

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/AnswerStatus.jsx
> +        if (props.stage === "Next") {
`Next`, `Answer` являются константами, лучше поместить их в отдельный модуль
 Например:
```
export const ANSWER_STAGE = {
    NEXT = 'NEXT',
    ANSWER = 'ANSWER'
}
```

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/OptionList.jsx
> +        if (this.props.stage === 'Next') {
Очень странная конструкция.

2018-08-23 11:16 UTC, KeinAsylum commented on src/components/Answer.jsx
> +        this.setState({
Можно так: `this.setState({stage});`

2018-08-24 12:19 UTC, KeinAsylum requested changes

2018-08-24 12:19 UTC, KeinAsylum commented on src/components/App.jsx
> +                        <Quiz questions={this.props.questions} onScoreChange={this.handleScoreChange} onQuizFinish={this.handleQuizFinish} /> :
Можно в `onQuizFinish` сразу передать score

2018-08-24 12:19 UTC, KeinAsylum commented on src/components/quiz/Quiz.jsx
> +        if (this.isLastQuestion()) {
В render нельзя размещать подобную логику, для этого есть отдельный lifecycle метод: https://reactjs.org/docs/react-component.html#componentdidupdate

2018-08-24 12:19 UTC, KeinAsylum commented on src/components/quiz/Quiz.jsx
> +                    onScoreChange={this.onScoreChange}
Очень странно, что на событие onScoreChange вешается событие onScoreChange

2018-08-24 12:19 UTC, KeinAsylum commented on src/components/quiz/Quiz.jsx
> +    getCurrentQuestion = () => {
Важно единообразие или везде использовать стрелочные функции для методов, или везде делать `bind`

2018-08-24 12:19 UTC, KeinAsylum commented on src/components/quiz/Quiz.jsx
> +                    currentQuestionId={this.state.currentQuestionId + 1}
`this.state.currentQuestionId + 1` несет для `Progress` компонента другой смысл, это уже не `currentQuestionId`

2018-08-24 12:19 UTC, KeinAsylum commented on src/modules/AnswerStage.js
> +export default { NEXT, ANSWER }
Это `constants`. Давая наименование `AnswerStage`, складывается ощущение, что это компонент.  Лучше `answerStage`

2018-08-24 14:17 UTC, KeinAsylum approved these changes

2018-08-27 12:44 UTC, merged